#pragma once

#include <map>
#include <string>
#include <unordered_map>


 class AmmoType {
public:
    enum Type {
        Compact,
        Medium,
        Long,
        Shell,
        Harpoon,
        CompactBolt,
        ChuKoNuBolt,
        Bolt,
        Nitro,
        Dolch,
        Arrow,
        Slug,
        LongPistol,
        Haymaker,
        Uppercut,
        CompactPistol,
        Spitzer
    };
};

 class ActionType {
 public:
	 enum Type {
		 BoltAction,
		 LeverAction,
		 PumpAction,
		 SemiAuto,
		 SingleAction,
		 SingleShotBreechLoading,
		 BreakAction,
		 DrawAndLatch,
		 DrawAndRelease,
         DoubleAction
	 };
 };


 class SlotSize {
 public:
	 enum Type {
		 Small,
		 Medium,
		 Large
	 };
 };





inline std::unordered_map<AmmoType::Type, float> AmmoDrag{
    {AmmoType::Long, 0.45f},
    {AmmoType::Medium, 0.25f},
    {AmmoType::Compact, 0.00f},
	{AmmoType::Shell, 0.15f},
	{AmmoType::Harpoon, 0.55f},
	{AmmoType::CompactBolt, 0.20f},
	{AmmoType::ChuKoNuBolt, 0.30f},
	{AmmoType::Bolt, 0.40f},
	{AmmoType::Nitro, 0.50f},
	{AmmoType::Dolch, 0.50f},
	{AmmoType::Arrow, 0.60f},
	{AmmoType::Slug, 0.45f},
	{AmmoType::LongPistol, 0.35f},
	{AmmoType::Haymaker, 0.45f},
	{AmmoType::Uppercut, 0.45f},
	{AmmoType::CompactPistol, 0.00f},
};

inline std::unordered_map<ActionType::Type, float> ActionMult{
    {ActionType::BoltAction, 0.5f},
    {ActionType::LeverAction, 0.5f},
    {ActionType::PumpAction, 0.5f},
    {ActionType::SemiAuto, 1.3f},
    {ActionType::SingleAction, 0.5f},
    {ActionType::SingleShotBreechLoading, -0.15f},
    {ActionType::BreakAction, 0.50f},
    {ActionType::DrawAndLatch, 0.6f},
    {ActionType::DrawAndRelease, 0.5f},
    {ActionType::DoubleAction, 0.28f}
};

inline std::unordered_map<SlotSize::Type, float> barrelMult{
	{SlotSize::Small, 1.0f},
	{SlotSize::Medium, 0.25f},
	{SlotSize::Large, 0.0f}
};

inline std::unordered_map<AmmoType::Type, float> DropMult{
    {AmmoType::Long, 1.75f},
	{AmmoType::Spitzer, 1.70f},
    {AmmoType::Medium, 1.25f},
    {AmmoType::Compact, 0.55f},
	{AmmoType::Shell, 1.0f},
	{AmmoType::Harpoon, 2.0f},
	{AmmoType::CompactBolt, 1.1f},
	{AmmoType::ChuKoNuBolt, 1.3f},
	{AmmoType::Bolt, 1.5f},
	{AmmoType::Nitro, 2.5f},
	{AmmoType::Dolch, 0.75f},
	{AmmoType::Arrow, 1.8f},
	{AmmoType::Slug, 2.5f},
	{AmmoType::LongPistol, 1.0f},
	{AmmoType::Haymaker, 4.5f},
	{AmmoType::Uppercut, 2.75f},
	{AmmoType::CompactPistol, 0.75f},


};

inline std::unordered_map<AmmoType::Type, float> DropAdd{
    {AmmoType::Long, 0.25},
	{AmmoType::Spitzer, 0.20f},
    {AmmoType::Medium, -0.75f},
    {AmmoType::Compact, -1.0f},
	{AmmoType::Shell, -0.50f},
	{AmmoType::Slug, 0.5f},
};
 struct Weapon {
    std::string name;
    AmmoType::Type ammoType;
    float muzzleVelocity;
    int dropRange;
    ActionType::Type action;
	SlotSize::Type slot;

};


inline static const char* weaponNames[] = {
    "Carbine Base",
    "Carbine FMJ",
    "Carbine Silencer Base",
    "Carbine Silencer FMJ",
    "Carbine Silencer Subsonic",
    "Carbine Subsonic",
    "Auto-4 Shorty Base",
    "Auto-4 Shorty Flechette",
    "Auto-4 Shorty Penny Shot",
    "Auto-4 Shorty Slug",
    "Auto-5 Base",
    "Auto-5 Flechette",
    "Auto-5 Penny Shot",
    "Auto-5 Slug",
    "Berthier Base",
    "Berthier Incendiary",
    "Bomb Lance Base",
    "Bomb Lance Dragon Breath",
    "Bomb Lance Harpoon",
    "Bomb Lance Steel Ball",
    "Bomb Lance Waxed Frag Charge",
    "Bomb Launcher Base",
    "Bomb Launcher Dragon Breath",
    "Bomb Launcher Harpoon",
    "Bomb Launcher Steel Ball",
    "Bomb Launcher Waxed Frag Charge",
    "Bornheim No. 3 Base",
    "Bornheim No. 3 High Velocity",
    "Bornheim No. 3 Incendiary",
    "Bornheim No. 3 Match Base",
    "Bornheim No. 3 Match High Velocity",
    "Bornheim No. 3 Match Incendiary",
    "Bornheim No. 3 Match Subsonic",
    "Bornheim No. 3 Silencer Base",
    "Bornheim No. 3 Silencer High Velocity",
    "Bornheim No. 3 Silencer Incendiary",
    "Bornheim No. 3 Silencer Subsonic",
    "Bornheim No. 3 Subsonic",
    "Centennial Base",
    "Centennial Dumdum",
    "Centennial FMJ",
    "Centennial High Velocity",
    "Centennial Pointman Base",
    "Centennial Pointman Dumdum",
    "Centennial Pointman FMJ",
    "Centennial Pointman High Velocity",
    "Centennial Pointman Poison",
    "Centennial Pointman Subsonic",
    "Centennial Poison",
    "Centennial Shorty Base",
    "Centennial Shorty Dumdum",
    "Centennial Shorty FMJ",
    "Centennial Shorty High Velocity",
    "Centennial Shorty Poison",
    "Centennial Shorty Silencer Base",
    "Centennial Shorty Silencer Dumdum",
    "Centennial Shorty Silencer FMJ",
    "Centennial Shorty Silencer High Velocity",
    "Centennial Shorty Silencer Poison",
    "Centennial Shorty Silencer Subsonic",
    "Centennial Shorty Subsonic",
    "Centennial Subsonic",
    "Centennial Trauma Base",
    "Centennial Trauma Dumdum",
    "Centennial Trauma FMJ",
    "Centennial Trauma High Velocity",
    "Centennial Trauma Poison",
    "Centennial Trauma Subsonic",
    "Chu Ko Nu Base",
    "Chu Ko Nu Explosive Bolt",
    "Chu Ko Nu Incendiary Bolt",
    "Conversion Base",
    "Conversion Chain Pistol Base",
    "Conversion Chain Pistol Dumdum",
    "Conversion Chain Pistol FMJ",
    "Conversion Dumdum",
    "Conversion FMJ",
    "Crossbow Base",
    "Crossbow Explosive Bolt",
    "Crossbow Shot Bolt",
    "Crossbow Steel Bolt",
    "Dolch 96 Base",
    "Dolch 96 Dumdum",
    "Dolch 96 FMJ",
    "Drilling Base",
    "Drilling Dumdum",
    "Drilling Flechette",
    "Drilling FMJ",
    "Drilling High Velocity",
    "Drilling Penny Shot",
    "Drilling Shorty Base",
    "Drilling Shorty Dumdum",
    "Drilling Shorty Flechette",
    "Drilling Shorty FMJ",
    "Drilling Shorty High Velocity",
    "Drilling Shorty Penny Shot",
    "Drilling Shorty Slug",
    "Drilling Slug",
    "Frontier 73C Base",
    "Frontier 73C FMJ",
    "Frontier 73C High Velocity",
    "Frontier 73C Incendiary",
    "Frontier 73C Poison",
    "Frontier 73C Silencer Base",
    "Frontier 73C Silencer FMJ",
    "Frontier 73C Silencer High Velocity",
    "Frontier 73C Silencer Incendiary",
    "Frontier 73C Silencer Poison",
    "Frontier 73C Silencer Subsonic",
    "Frontier 73C Subsonic",
    "Hand Crossbow Base",
    "Hand Crossbow Chaos Bolt",
    "Hand Crossbow Choke Bolt",
    "Hand Crossbow Dragon Bolt",
    "Hand Crossbow Poison Bolt",
    "Haymaker Base",
    "Haymaker Dragon Breath",
    "Haymaker FMJ",
    "Haymaker Poison",
    "Haymaker Slug",
    "Haymaker Starshell",
    "Hunting Bow Base",
    "Hunting Bow Concertina Arrow",
    "Hunting Bow Frag Arrow",
    "Hunting Bow Poison Arrow",
    "Infantry 73L Base",
    "Infantry 73L FMJ",
    "Infantry 73L High Velocity",
    "Infantry 73L Incendiary",
    "Infantry 73L Poison",
    "Infantry 73L Subsonic",
    "Krag Base",
    "Krag FMJ",
    "Krag Incendiary",
    "Krag Silencer Base",
    "Krag Silencer FMJ",
    "Krag Silencer Incendiary",
    "Krag Silencer Subsonic",
    "Krag Subsonic",
    "Lebel Base",
    "Lebel Incendiary",
	"Lebel Spitzer",
    "LeMat Base",
    "LeMat Carbine Base",
    "LeMat Carbine Dragon Breath",
    "LeMat Carbine FMJ",
    "LeMat Carbine Incendiary",
    "LeMat Carbine Slug",
    "LeMat Carbine Starshell",
    "LeMat Dragon Breath",
    "LeMat FMJ",
    "LeMat Incendiary",
    "LeMat Slug",
    "LeMat Starshell",
    "Mako Base",
    "Mako Explosive",
    "Mako FMJ",
    "Marathon Base",
    "Marathon FMJ",
    "Marathon High Velocity",
    "Marathon Incendiary",
    "Marathon Poison",
    "Martini-Henry Base",
    "Martini-Henry Explosive",
    "Martini-Henry FMJ",
    "Martini-Henry High Velocity",
    "Martini-Henry Incendiary",
    "Mosin Obrez Base",
    "Mosin Obrez Incendiary",
    "Mosin Obrez Match Base",
    "Mosin Obrez Match Incendiary",
    "Mosin-Nagant Avtomat Base",
    "Mosin-Nagant Avtomat Spitzer",
    "Mosin-Nagant Avtomat Incendiary",
    "Mosin-Nagant Base",
    "Mosin-Nagant Spitzer",
    "Mosin-Nagant Incendiary",
    "Nagant M1895 Base",
    "Nagant M1895 Dumdum",
    "Nagant M1895 High Velocity",
    "Nagant M1895 Poison",
    "Nagant M1895 Silencer Base",
    "Nagant M1895 Silencer Dumdum",
    "Nagant M1895 Silencer High Velocity",
    "Nagant M1895 Silencer Poison",
    "Nagant M1895 Silencer Subsonic",
    "Nagant M1895 Subsonic",
    "New Army Base",
    "New Army Dumdum",
    "New Army FMJ",
    "Nitro Express Base",
    "Nitro Express Explosive",
    "Nitro Express Shredder",
    "Officer Base",
    "Officer Carbine Base",
    "Officer Carbine Dumdum",
    "Officer Carbine High Velocity",
    "Officer Carbine Poison",
    "Officer Carbine Subsonic",
    "Officer Dumdum",
    "Officer High Velocity",
    "Officer Poison",
    "Officer Subsonic",
    "Pax Base",
    "Pax Dumdum",
    "Pax FMJ",
    "Pax High Velocity",
    "Pax Incendiary",
    "Pax Poison",
    "Pax Trueshot Base",
    "Pax Trueshot Dumdum",
    "Pax Trueshot FMJ",
    "Pax Trueshot High Velocity",
    "Pax Trueshot Incendiary",
    "Pax Trueshot Poison",
    "Ranger 73 Base",
    "Ranger 73 FMJ",
    "Ranger 73 High Velocity",
    "Ranger 73 Incendiary",
    "Ranger 73 Poison",
    "Ranger 73 Subsonic",
    "Rival 78 Base",
    "Rival 78 Dragon Breath",
    "Rival 78 Flechette",
    "Rival 78 Penny Shot",
    "Rival 78 Shorty Base",
    "Rival 78 Shorty Dragon Breath",
    "Rival 78 Shorty Flechette",
    "Rival 78 Shorty Penny Shot",
    "Rival 78 Shorty Slug",
    "Rival 78 Slug",
    "Rival 78 Trauma Base",
    "Rival 78 Trauma Dragon Breath",
    "Rival 78 Trauma Flechette",
    "Rival 78 Trauma Penny Shot",
    "Rival 78 Trauma Slug",
    "Romero 77 Base",
    "Romero 77 Dragon Breath",
    "Romero 77 Penny Shot",
    "Romero 77 Shorty Base",
    "Romero 77 Shorty Dragon Breath",
    "Romero 77 Shorty Penny Shot",
    "Romero 77 Shorty Slug",
    "Romero 77 Shorty Starshell",
    "Romero 77 Slug",
    "Romero 77 Starshell",
    "Scottfield Base",
    "Scottfield Dumdum",
    "Scottfield FMJ",
    "Scottfield High Velocity",
    "Scottfield Incendiary",
    "Slate Base",
    "Slate Penny Shot",
    "Slate Slug",
    "Sparks Base",
    "Sparks FMJ",
    "Sparks Incendiary",
    "Sparks Pistol Base",
    "Sparks Pistol FMJ",
    "Sparks Pistol Incendiary",
    "Sparks Pistol Poison",
    "Sparks Pistol Silencer Base",
    "Sparks Pistol Silencer FMJ",
    "Sparks Pistol Silencer Incendiary",
    "Sparks Pistol Silencer Poison",
    "Sparks Pistol Silencer Subsonic",
    "Sparks Pistol Subsonic",
    "Sparks Poison",
    "Sparks Silencer Base",
    "Sparks Silencer FMJ",
    "Sparks Silencer Incendiary",
    "Sparks Silencer Poison",
    "Sparks Silencer Subsonic",
    "Sparks Subsonic",
    "Specter Base",
    "Specter Dragon Breath",
    "Specter Flechette",
    "Specter Penny Shot",
    "Specter Shorty Base",
    "Specter Shorty Dragon Breath",
    "Specter Shorty Flechette",
    "Specter Shorty Penny Shot",
    "Specter Shorty Slug",
    "Specter Slug",
    "Springfield Base",
    "Springfield Dumdum",
    "Springfield Explosive",
    "Springfield High Velocity",
    "Springfield Poison",
    "Springfield Shorty Base",
    "Springfield Shorty Dumdum",
    "Springfield Shorty Explosive",
    "Springfield Shorty High Velocity",
    "Springfield Shorty Poison",
    "Terminus Base",
    "Terminus Dragon Breath",
    "Terminus Flechette",
    "Terminus Penny Shot",
    "Terminus Shorty Base",
    "Terminus Shorty Dragon Breath",
    "Terminus Shorty Flechette",
    "Terminus Shorty Penny Shot",
    "Terminus Shorty Slug",
    "Terminus Slug",
    "Uppercut Base",
    "Uppercut Explosive",
    "Uppercut FMJ",
    "Uppercut Incendiary",
    "Vandal 73C Base",
    "Vandal 73C FMJ",
    "Vandal 73C High Velocity",
    "Vandal 73C Incendiary",
    "Vandal 73C Poison",
    "Vandal 73C Subsonic",
    "Vetterli 71 Base",
    "Vetterli 71 Cyclone Base",
    "Vetterli 71 Cyclone FMJ",
    "Vetterli 71 Cyclone High Velocity",
    "Vetterli 71 Cyclone Incendiary",
    "Vetterli 71 Cyclone Subsonic",
    "Vetterli 71 FMJ",
    "Vetterli 71 High Velocity",
    "Vetterli 71 Incendiary",
    "Vetterli 71 Silencer Base",
    "Vetterli 71 Silencer FMJ",
    "Vetterli 71 Silencer High Velocity",
    "Vetterli 71 Silencer Incendiary",
    "Vetterli 71 Silencer Subsonic",
    "Vetterli 71 Subsonic",
    "Baseball Bat Base",
    "Cavalry Saber Base",
    "Combat Axe Base",
    "Katana Base",
    "Machete Base",
    "Railroad Hammer Base",
};




inline std::map<std::string, Weapon> weapons = {
{ "Carbine Base", { "Carbine Base", AmmoType::Type::Medium, 340.0f, 115, ActionType::LeverAction, SlotSize::Large } },
{ "Carbine FMJ", { "Carbine FMJ", AmmoType::Type::Medium, 272.0f, 105, ActionType::LeverAction, SlotSize::Large } },
{ "Carbine Silencer Base", { "Carbine Silencer Base", AmmoType::Type::Medium, 289.0f, 105, ActionType::LeverAction, SlotSize::Large } },
{ "Carbine Silencer FMJ", { "Carbine Silencer FMJ", AmmoType::Type::Medium, 218.0f, 90, ActionType::LeverAction, SlotSize::Large } },
{ "Carbine Silencer Subsonic", { "Carbine Silencer Subsonic", AmmoType::Type::Medium, 229.0f, 95, ActionType::LeverAction, SlotSize::Large } },
{ "Carbine Subsonic", { "Carbine Subsonic", AmmoType::Type::Medium, 242.0f, 95, ActionType::LeverAction, SlotSize::Large } },
{ "Auto-4 Shorty Base", { "Auto-4 Shorty Base", AmmoType::Type::Shell, 350.0f, 20, ActionType::SemiAuto, SlotSize::Medium } },
{ "Auto-4 Shorty Flechette", { "Auto-4 Shorty Flechette", AmmoType::Type::Shell, 350.0f, 20, ActionType::SemiAuto, SlotSize::Medium } },
{ "Auto-4 Shorty Penny Shot", { "Auto-4 Shorty Penny Shot", AmmoType::Type::Shell, 350.0f, 20, ActionType::SemiAuto, SlotSize::Medium } },
{ "Auto-4 Shorty Slug", { "Auto-4 Shorty Slug", AmmoType::Type::Shell, 350.0f, 20, ActionType::SemiAuto, SlotSize::Medium } },
{ "Auto-5 Base", { "Auto-5 Base", AmmoType::Type::Shell, 425.0f, 30, ActionType::SemiAuto, SlotSize::Large } },
{ "Auto-5 Flechette", { "Auto-5 Flechette", AmmoType::Type::Shell, 425.0f, 30, ActionType::SemiAuto, SlotSize::Large } },
{ "Auto-5 Penny Shot", { "Auto-5 Penny Shot", AmmoType::Type::Shell, 425.0f, 30, ActionType::SemiAuto, SlotSize::Large } },
{ "Auto-5 Slug", { "Auto-5 Slug", AmmoType::Type::Shell, 425.0f, 30, ActionType::SemiAuto, SlotSize::Large } },
{ "Berthier Base", { "Berthier Base", AmmoType::Type::Long, 590.0f, 120, ActionType::BoltAction, SlotSize::Large } },
{ "Berthier Incendiary", { "Berthier Incendiary", AmmoType::Type::Long, 590.0f, 120, ActionType::BoltAction, SlotSize::Large } },
{ "Bomb Lance Base", { "Bomb Lance Base", AmmoType::Type::Harpoon, 60.0f, 5, ActionType::DrawAndLatch, SlotSize::Large } },
{ "Bomb Lance Dragon Breath", { "Bomb Lance Dragon Breath", AmmoType::Type::Harpoon, 100.0f, 5, ActionType::DrawAndLatch, SlotSize::Large } },
{ "Bomb Lance Harpoon", { "Bomb Lance Harpoon", AmmoType::Type::Harpoon, 80.0f, 5, ActionType::DrawAndLatch, SlotSize::Large } },
{ "Bomb Lance Steel Ball", { "Bomb Lance Steel Ball", AmmoType::Type::Harpoon, 450.0f, 5, ActionType::DrawAndLatch, SlotSize::Large } },
{ "Bomb Lance Waxed Frag Charge", { "Bomb Lance Waxed Frag Charge", AmmoType::Type::Harpoon, 60.0f, 5, ActionType::DrawAndLatch, SlotSize::Large } },
{ "Bomb Launcher Base", { "Bomb Launcher Base", AmmoType::Type::Harpoon, 60.0f, 5, ActionType::DrawAndLatch, SlotSize::Medium } },
{ "Bomb Launcher Dragon Breath", { "Bomb Launcher Dragon Breath", AmmoType::Type::Harpoon, 100.0f, 5, ActionType::DrawAndLatch, SlotSize::Medium } },
{ "Bomb Launcher Harpoon", { "Bomb Launcher Harpoon", AmmoType::Type::Harpoon, 80.0f, 5, ActionType::DrawAndLatch, SlotSize::Medium } },
{ "Bomb Launcher Steel Ball", { "Bomb Launcher Steel Ball", AmmoType::Type::Harpoon, 450.0f, 5, ActionType::DrawAndLatch, SlotSize::Medium } },
{ "Bomb Launcher Waxed Frag Charge", { "Bomb Launcher Waxed Frag Charge", AmmoType::Type::Harpoon, 60.0f, 5, ActionType::DrawAndLatch, SlotSize::Medium } },
{ "Bornheim No. 3 Base", { "Bornheim No. 3 Base", AmmoType::Type::Compact, 380.0f, 80, ActionType::SemiAuto, SlotSize::Small } },
{ "Bornheim No. 3 High Velocity", { "Bornheim No. 3 High Velocity", AmmoType::Type::Compact, 455.0f, 85, ActionType::SemiAuto, SlotSize::Small } },
{ "Bornheim No. 3 Incendiary", { "Bornheim No. 3 Incendiary", AmmoType::Type::Compact, 380.0f, 80, ActionType::SemiAuto, SlotSize::Small } },
{ "Bornheim No. 3 Match Base", { "Bornheim No. 3 Match Base", AmmoType::Type::Compact, 400.0f, 85, ActionType::SemiAuto, SlotSize::Small } },
{ "Bornheim No. 3 Match High Velocity", { "Bornheim No. 3 Match High Velocity", AmmoType::Type::Compact, 475.0f, 90, ActionType::SemiAuto, SlotSize::Small } },
{ "Bornheim No. 3 Match Incendiary", { "Bornheim No. 3 Match Incendiary", AmmoType::Type::Compact, 400.0f, 85, ActionType::SemiAuto, SlotSize::Small } },
{ "Bornheim No. 3 Match Subsonic", { "Bornheim No. 3 Match Subsonic", AmmoType::Type::Compact, 263.0f, 60, ActionType::SemiAuto, SlotSize::Small } },
{ "Bornheim No. 3 Silencer Base", { "Bornheim No. 3 Silencer Base", AmmoType::Type::Compact, 323.0f, 70, ActionType::SemiAuto, SlotSize::Small } },
{ "Bornheim No. 3 Silencer High Velocity", { "Bornheim No. 3 Silencer High Velocity", AmmoType::Type::Compact, 398.0f, 75, ActionType::SemiAuto, SlotSize::Small } },
{ "Bornheim No. 3 Silencer Incendiary", { "Bornheim No. 3 Silencer Incendiary", AmmoType::Type::Compact, 323.0f, 70, ActionType::SemiAuto, SlotSize::Small } },
{ "Bornheim No. 3 Silencer Subsonic", { "Bornheim No. 3 Silencer Subsonic", AmmoType::Type::Compact, 236.0f, 55, ActionType::SemiAuto, SlotSize::Small } },
{ "Bornheim No. 3 Subsonic", { "Bornheim No. 3 Subsonic", AmmoType::Type::Compact, 256.0f, 60, ActionType::SemiAuto, SlotSize::Small } },
{ "Centennial Base", { "Centennial Base", AmmoType::Type::Medium, 600.0f, 140, ActionType::LeverAction, SlotSize::Large } },
{ "Centennial Dumdum", { "Centennial Dumdum", AmmoType::Type::Medium, 480.0f, 125, ActionType::LeverAction, SlotSize::Large } },
{ "Centennial FMJ", { "Centennial FMJ", AmmoType::Type::Medium, 480.0f, 125, ActionType::LeverAction, SlotSize::Large } },
{ "Centennial High Velocity", { "Centennial High Velocity", AmmoType::Type::Medium, 725.0f, 155, ActionType::LeverAction, SlotSize::Large } },
{ "Centennial Pointman Base", { "Centennial Pointman Base", AmmoType::Type::Medium, 540.0f, 110, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Pointman Dumdum", { "Centennial Pointman Dumdum", AmmoType::Type::Medium, 432.0f, 95, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Pointman FMJ", { "Centennial Pointman FMJ", AmmoType::Type::Medium, 432.0f, 95, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Pointman High Velocity", { "Centennial Pointman High Velocity", AmmoType::Type::Medium, 640.0f, 125, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Pointman Poison", { "Centennial Pointman Poison", AmmoType::Type::Medium, 540.0f, 110, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Pointman Subsonic", { "Centennial Pointman Subsonic", AmmoType::Type::Medium, 312.0f, 80, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Poison", { "Centennial Poison", AmmoType::Type::Medium, 600.0f, 140, ActionType::LeverAction, SlotSize::Large } },
{ "Centennial Shorty Base", { "Centennial Shorty Base", AmmoType::Type::Medium, 540.0f, 110, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Shorty Dumdum", { "Centennial Shorty Dumdum", AmmoType::Type::Medium, 432.0f, 95, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Shorty FMJ", { "Centennial Shorty FMJ", AmmoType::Type::Medium, 432.0f, 95, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Shorty High Velocity", { "Centennial Shorty High Velocity", AmmoType::Type::Medium, 640.0f, 125, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Shorty Poison", { "Centennial Shorty Poison", AmmoType::Type::Medium, 540.0f, 110, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Shorty Silencer Base", { "Centennial Shorty Silencer Base", AmmoType::Type::Medium, 459.0f, 100, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Shorty Silencer Dumdum", { "Centennial Shorty Silencer Dumdum", AmmoType::Type::Medium, 367.0f, 85, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Shorty Silencer FMJ", { "Centennial Shorty Silencer FMJ", AmmoType::Type::Medium, 367.0f, 85, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Shorty Silencer High Velocity", { "Centennial Shorty Silencer High Velocity", AmmoType::Type::Medium, 559.0f, 110, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Shorty Silencer Poison", { "Centennial Shorty Silencer Poison", AmmoType::Type::Medium, 459.0f, 100, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Shorty Silencer Subsonic", { "Centennial Shorty Silencer Subsonic", AmmoType::Type::Medium, 283.0f, 75, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Shorty Subsonic", { "Centennial Shorty Subsonic", AmmoType::Type::Medium, 312.0f, 80, ActionType::LeverAction, SlotSize::Medium } },
{ "Centennial Subsonic", { "Centennial Subsonic", AmmoType::Type::Medium, 333.0f, 105, ActionType::LeverAction, SlotSize::Large } },
{ "Centennial Trauma Base", { "Centennial Trauma Base", AmmoType::Type::Medium, 600.0f, 140, ActionType::LeverAction, SlotSize::Large } },
{ "Centennial Trauma Dumdum", { "Centennial Trauma Dumdum", AmmoType::Type::Medium, 480.0f, 125, ActionType::LeverAction, SlotSize::Large } },
{ "Centennial Trauma FMJ", { "Centennial Trauma FMJ", AmmoType::Type::Medium, 480.0f, 125, ActionType::LeverAction, SlotSize::Large } },
{ "Centennial Trauma High Velocity", { "Centennial Trauma High Velocity", AmmoType::Type::Medium, 725.0f, 155, ActionType::LeverAction, SlotSize::Large } },
{ "Centennial Trauma Poison", { "Centennial Trauma Poison", AmmoType::Type::Medium, 600.0f, 140, ActionType::LeverAction, SlotSize::Large } },
{ "Centennial Trauma Subsonic", { "Centennial Trauma Subsonic", AmmoType::Type::Medium, 333.0f, 105, ActionType::LeverAction, SlotSize::Large } },
{ "Chu Ko Nu Base", { "Chu Ko Nu Base", AmmoType::Type::ChuKoNuBolt, 125.0f, 17, ActionType::SemiAuto, SlotSize::Medium } },
{ "Chu Ko Nu Explosive Bolt", { "Chu Ko Nu Explosive Bolt", AmmoType::Type::ChuKoNuBolt, 80.0f, 10, ActionType::SemiAuto, SlotSize::Medium } },
{ "Chu Ko Nu Incendiary Bolt", { "Chu Ko Nu Incendiary Bolt", AmmoType::Type::ChuKoNuBolt, 125.0f, 17, ActionType::SemiAuto, SlotSize::Medium } },
{ "Conversion Base", { "Conversion Base", AmmoType::Type::Compact, 300.0f, 75, ActionType::SingleAction, SlotSize::Small } },
{ "Conversion Chain Pistol Base", { "Conversion Chain Pistol Base", AmmoType::Type::Compact, 300.0f, 75, ActionType::SingleAction, SlotSize::Small } },
{ "Conversion Chain Pistol Dumdum", { "Conversion Chain Pistol Dumdum", AmmoType::Type::Compact, 270.0f, 70, ActionType::SingleAction, SlotSize::Small } },
{ "Conversion Chain Pistol FMJ", { "Conversion Chain Pistol FMJ", AmmoType::Type::Compact, 270.0f, 70, ActionType::SingleAction, SlotSize::Small } },
{ "Conversion Dumdum", { "Conversion Dumdum", AmmoType::Type::Compact, 270.0f, 70, ActionType::SingleAction, SlotSize::Small } },
{ "Conversion FMJ", { "Conversion FMJ", AmmoType::Type::Compact, 270.0f, 70, ActionType::SingleAction, SlotSize::Small } },
{ "Crossbow Base", { "Crossbow Base", AmmoType::Type::Bolt, 150.0f, 20, ActionType::DrawAndLatch, SlotSize::Large } },
{ "Crossbow Explosive Bolt", { "Crossbow Explosive Bolt", AmmoType::Type::Bolt, 60.0f, 10, ActionType::DrawAndLatch, SlotSize::Large } },
{ "Crossbow Shot Bolt", { "Crossbow Shot Bolt", AmmoType::Type::Bolt, 100.0f, 15, ActionType::DrawAndLatch, SlotSize::Large } },
{ "Crossbow Steel Bolt", { "Crossbow Steel Bolt", AmmoType::Type::Bolt, 225.0f, 35, ActionType::DrawAndLatch, SlotSize::Large } },
{ "Dolch 96 Base", { "Dolch 96 Base", AmmoType::Type::Dolch, 440.0f, 70, ActionType::SemiAuto, SlotSize::Medium } },
{ "Dolch 96 Dumdum", { "Dolch 96 Dumdum", AmmoType::Type::Dolch, 390.0f, 65, ActionType::SemiAuto, SlotSize::Medium } },
{ "Dolch 96 FMJ", { "Dolch 96 FMJ", AmmoType::Type::Dolch, 390.0f, 65, ActionType::SemiAuto, SlotSize::Medium } },
{ "Drilling Base", { "Drilling Base", AmmoType::Type::Medium, 530.0f, 145, ActionType::BreakAction, SlotSize::Large } },
{ "Drilling Dumdum", { "Drilling Dumdum", AmmoType::Type::Medium, 371.0f, 125, ActionType::BreakAction, SlotSize::Large } },
{ "Drilling Flechette", { "Drilling Flechette", AmmoType::Type::Shell, 450.0f, 20, ActionType::BreakAction, SlotSize::Large } },
{ "Drilling FMJ", { "Drilling FMJ", AmmoType::Type::Medium, 371.0f, 125, ActionType::BreakAction, SlotSize::Large } },
{ "Drilling High Velocity", { "Drilling High Velocity", AmmoType::Type::Medium, 655.0f, 165, ActionType::BreakAction, SlotSize::Large } },
{ "Drilling Penny Shot", { "Drilling Penny Shot", AmmoType::Type::Shell, 450.0f, 20, ActionType::BreakAction, SlotSize::Large } },
{ "Drilling Shorty Base", { "Drilling Shorty Base", AmmoType::Type::Medium, 424.0f, 120, ActionType::BreakAction, SlotSize::Medium } },
{ "Drilling Shorty Dumdum", { "Drilling Shorty Dumdum", AmmoType::Type::Medium, 340.0f, 105, ActionType::BreakAction, SlotSize::Medium } },
{ "Drilling Shorty Flechette", { "Drilling Shorty Flechette", AmmoType::Type::Shell, 375.0f, 20, ActionType::BreakAction, SlotSize::Medium } },
{ "Drilling Shorty FMJ", { "Drilling Shorty FMJ", AmmoType::Type::Medium, 340.0f, 105, ActionType::BreakAction, SlotSize::Medium } },
{ "Drilling Shorty High Velocity", { "Drilling Shorty High Velocity", AmmoType::Type::Medium, 524.0f, 135, ActionType::BreakAction, SlotSize::Medium } },
{ "Drilling Shorty Penny Shot", { "Drilling Shorty Penny Shot", AmmoType::Type::Shell, 375.0f, 15, ActionType::BreakAction, SlotSize::Medium } },
{ "Drilling Shorty Slug", { "Drilling Shorty Slug", AmmoType::Type::Shell, 375.0f, 20, ActionType::BreakAction, SlotSize::Medium } },
{ "Drilling Slug", { "Drilling Slug", AmmoType::Type::Shell, 450.0f, 20, ActionType::BreakAction, SlotSize::Large } },
{ "Frontier 73C Base", { "Frontier 73C Base", AmmoType::Type::Compact, 400.0f, 140, ActionType::LeverAction, SlotSize::Large } },
{ "Frontier 73C FMJ", { "Frontier 73C FMJ", AmmoType::Type::Compact, 330.0f, 125, ActionType::LeverAction, SlotSize::Large } },
{ "Frontier 73C High Velocity", { "Frontier 73C High Velocity", AmmoType::Type::Compact, 500.0f, 160, ActionType::LeverAction, SlotSize::Large } },
{ "Frontier 73C Incendiary", { "Frontier 73C Incendiary", AmmoType::Type::Compact, 400.0f, 140, ActionType::LeverAction, SlotSize::Large } },
{ "Frontier 73C Poison", { "Frontier 73C Poison", AmmoType::Type::Compact, 400.0f, 140, ActionType::LeverAction, SlotSize::Large } },
{ "Frontier 73C Silencer Base", { "Frontier 73C Silencer Base", AmmoType::Type::Compact, 340.0f, 120, ActionType::LeverAction, SlotSize::Large } },
{ "Frontier 73C Silencer FMJ", { "Frontier 73C Silencer FMJ", AmmoType::Type::Compact, 272.0f, 105, ActionType::LeverAction, SlotSize::Large } },
{ "Frontier 73C Silencer High Velocity", { "Frontier 73C Silencer High Velocity", AmmoType::Type::Compact, 440.0f, 135, ActionType::LeverAction, SlotSize::Large } },
{ "Frontier 73C Silencer Incendiary", { "Frontier 73C Silencer Incendiary", AmmoType::Type::Compact, 340.0f, 120, ActionType::LeverAction, SlotSize::Large } },
{ "Frontier 73C Silencer Poison", { "Frontier 73C Silencer Poison", AmmoType::Type::Compact, 340.0f, 120, ActionType::LeverAction, SlotSize::Large } },
{ "Frontier 73C Silencer Subsonic", { "Frontier 73C Silencer Subsonic", AmmoType::Type::Compact, 242.0f, 100, ActionType::LeverAction, SlotSize::Large } },
{ "Frontier 73C Subsonic", { "Frontier 73C Subsonic", AmmoType::Type::Compact, 263.0f, 110, ActionType::LeverAction, SlotSize::Large } },
{ "Hand Crossbow Base", { "Hand Crossbow Base", AmmoType::Type::CompactBolt, 100.0f, 15, ActionType::DrawAndLatch, SlotSize::Small } },
{ "Hand Crossbow Chaos Bolt", { "Hand Crossbow Chaos Bolt", AmmoType::Type::CompactBolt, 50.0f, 15, ActionType::DrawAndLatch, SlotSize::Small } },
{ "Hand Crossbow Choke Bolt", { "Hand Crossbow Choke Bolt", AmmoType::Type::CompactBolt, 100.0f, 15, ActionType::DrawAndLatch, SlotSize::Small } },
{ "Hand Crossbow Dragon Bolt", { "Hand Crossbow Dragon Bolt", AmmoType::Type::CompactBolt, 100.0f, 15, ActionType::DrawAndLatch, SlotSize::Small } },
{ "Hand Crossbow Poison Bolt", { "Hand Crossbow Poison Bolt", AmmoType::Type::CompactBolt, 100.0f, 15, ActionType::DrawAndLatch, SlotSize::Small } },
{ "Haymaker Base", { "Haymaker Base", AmmoType::Type::Long, 530.0f, 65, ActionType::SingleAction, SlotSize::Small } },
{ "Haymaker Dragon Breath", { "Haymaker Dragon Breath", AmmoType::Type::Shell, 100.0f, 20, ActionType::SingleAction, SlotSize::Small} },
{ "Haymaker FMJ", { "Haymaker FMJ", AmmoType::Type::Long, 375.0f, 50, ActionType::SingleAction, SlotSize::Small } },
{ "Haymaker Poison", { "Haymaker Poison", AmmoType::Type::Long, 530.0f, 65, ActionType::SingleAction, SlotSize::Small } },
{ "Haymaker Slug", { "Haymaker Slug", AmmoType::Type::Shell, 350.0f, 20, ActionType::SingleAction, SlotSize::Small } },
{ "Haymaker Starshell", { "Haymaker Starshell", AmmoType::Type::Shell, 75.0f, 20, ActionType::SingleAction, SlotSize::Small } },
{ "Hunting Bow Base", { "Hunting Bow Base", AmmoType::Type::Arrow, 150.0f, 30, ActionType::DrawAndRelease, SlotSize::Medium } },
{ "Hunting Bow Concertina Arrow", { "Hunting Bow Concertina Arrow", AmmoType::Type::Arrow, 80.0f, 10, ActionType::DrawAndRelease, SlotSize::Medium } },
{ "Hunting Bow Frag Arrow", { "Hunting Bow Frag Arrow", AmmoType::Type::Arrow, 80.0f, 10, ActionType::DrawAndRelease, SlotSize::Medium } },
{ "Hunting Bow Poison Arrow", { "Hunting Bow Poison Arrow", AmmoType::Type::Arrow, 150.0f, 30, ActionType::DrawAndRelease, SlotSize::Medium } },
{ "Infantry 73L Base", { "Infantry 73L Base", AmmoType::Type::Compact, 400.0f, 145, ActionType::LeverAction, SlotSize::Large } },
{ "Infantry 73L FMJ", { "Infantry 73L FMJ", AmmoType::Type::Compact, 330.0f, 130, ActionType::LeverAction, SlotSize::Large } },
{ "Infantry 73L High Velocity", { "Infantry 73L High Velocity", AmmoType::Type::Compact, 525.0f, 170, ActionType::LeverAction, SlotSize::Large } },
{ "Infantry 73L Incendiary", { "Infantry 73L Incendiary", AmmoType::Type::Compact, 400.0f, 145, ActionType::LeverAction, SlotSize::Large } },
{ "Infantry 73L Poison", { "Infantry 73L Poison", AmmoType::Type::Compact, 400.0f, 145, ActionType::LeverAction, SlotSize::Large } },
{ "Infantry 73L Subsonic", { "Infantry 73L Subsonic", AmmoType::Type::Compact, 263.0f, 115, ActionType::LeverAction, SlotSize::Large } },
{ "Krag Base", { "Krag Base", AmmoType::Type::Long, 610.0f, 140, ActionType::BoltAction, SlotSize::Large } },
{ "Krag FMJ", { "Krag FMJ", AmmoType::Type::Long, 458.0f, 125, ActionType::BoltAction, SlotSize::Large } },
{ "Krag Incendiary", { "Krag Incendiary", AmmoType::Type::Long, 610.0f, 140, ActionType::BoltAction, SlotSize::Large } },
{ "Krag Silencer Base", { "Krag Silencer Base", AmmoType::Type::Long, 518.0f, 130, ActionType::BoltAction, SlotSize::Large } },
{ "Krag Silencer FMJ", { "Krag Silencer FMJ", AmmoType::Type::Long, 414.0f, 120, ActionType::BoltAction, SlotSize::Large } },
{ "Krag Silencer Incendiary", { "Krag Silencer Incendiary", AmmoType::Type::Long, 518.0f, 130, ActionType::BoltAction, SlotSize::Large } },
{ "Krag Silencer Subsonic", { "Krag Silencer Subsonic", AmmoType::Type::Long, 304.0f, 105, ActionType::BoltAction, SlotSize::Large } },
{ "Krag Subsonic", { "Krag Subsonic", AmmoType::Type::Long, 336.0f, 110, ActionType::BoltAction, SlotSize::Large } },
{ "Lebel Spitzer", { "Lebel Spitzer", AmmoType::Type::Spitzer, 850.0f, 165, ActionType::BoltAction, SlotSize::Large } },
{ "Lebel Base", { "Lebel Base", AmmoType::Type::Long, 630.0f, 140, ActionType::BoltAction, SlotSize::Large } },
{ "Lebel Incendiary", { "Lebel Incendiary", AmmoType::Type::Long, 630.0f, 140, ActionType::BoltAction, SlotSize::Large } },
{ "LeMat Base", { "LeMat Base", AmmoType::Type::Compact, 375.0f, 75, ActionType::SingleAction, SlotSize::Small } },
{ "LeMat Carbine Base", { "LeMat Carbine Base", AmmoType::Type::Compact, 460.0f, 130, ActionType::SingleAction, SlotSize::Large } },
{ "LeMat Carbine Dragon Breath", { "LeMat Carbine Dragon Breath", AmmoType::Type::Shell, 100.0f, 25, ActionType::SingleAction, SlotSize::Large } },
{ "LeMat Carbine FMJ", { "LeMat Carbine FMJ", AmmoType::Type::Compact, 415.0f, 120, ActionType::SingleAction, SlotSize::Large } },
{ "LeMat Carbine Incendiary", { "LeMat Carbine Incendiary", AmmoType::Type::Compact, 460.0f, 130, ActionType::SingleAction, SlotSize::Large } },
{ "LeMat Carbine Slug", { "LeMat Carbine Slug", AmmoType::Type::Shell, 425.0f, 25, ActionType::SingleAction, SlotSize::Large } },
{ "LeMat Carbine Starshell", { "LeMat Carbine Starshell", AmmoType::Type::Shell, 75.0f, 25, ActionType::SingleAction, SlotSize::Large } },
{ "LeMat Dragon Breath", { "LeMat Dragon Breath", AmmoType::Type::Shell, 100.0f, 10, ActionType::SingleAction, SlotSize::Small } },
{ "LeMat FMJ", { "LeMat FMJ", AmmoType::Type::Compact, 335.0f, 70, ActionType::SingleAction, SlotSize::Small } },
{ "LeMat Incendiary", { "LeMat Incendiary", AmmoType::Type::Compact, 375.0f, 75, ActionType::SingleAction, SlotSize::Small } },
{ "LeMat Slug", { "LeMat Slug", AmmoType::Type::Shell, 350.0f, 10, ActionType::SingleAction, SlotSize::Small } },
{ "LeMat Starshell", { "LeMat Starshell", AmmoType::Type::Shell, 75.0f, 10, ActionType::SingleAction, SlotSize::Small } },
{ "Mako Base", { "Mako Base", AmmoType::Type::Long, 540.0f, 115, ActionType::BoltAction, SlotSize::Large } },
{ "Mako Explosive", { "Mako Explosive", AmmoType::Type::Long, 432.0f, 85, ActionType::BoltAction, SlotSize::Large } },
{ "Mako FMJ", { "Mako FMJ", AmmoType::Type::Long, 405.0f, 95, ActionType::BoltAction, SlotSize::Large } },
{ "Marathon Base", { "Marathon Base", AmmoType::Type::Compact, 430.0f, 140, ActionType::PumpAction, SlotSize::Large } },
{ "Marathon FMJ", { "Marathon FMJ", AmmoType::Type::Compact, 360.0f, 125, ActionType::PumpAction, SlotSize::Large } },
{ "Marathon High Velocity", { "Marathon High Velocity", AmmoType::Type::Compact, 555.0f, 170, ActionType::PumpAction, SlotSize::Large } },
{ "Marathon Incendiary", { "Marathon Incendiary", AmmoType::Type::Compact, 430.0f, 140, ActionType::PumpAction, SlotSize::Large } },
{ "Marathon Poison", { "Marathon Poison", AmmoType::Type::Compact, 430.0f, 140, ActionType::PumpAction, SlotSize::Large } },
{ "Martini-Henry Base", { "Martini-Henry Base", AmmoType::Type::Long, 400.0f, 125, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Martini-Henry Explosive", { "Martini-Henry Explosive", AmmoType::Type::Long, 300.0f, 95, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Martini-Henry FMJ", { "Martini-Henry FMJ", AmmoType::Type::Long, 320.0f, 110, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Martini-Henry High Velocity", { "Martini-Henry High Velocity", AmmoType::Type::Long, 500.0f, 140, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Martini-Henry Incendiary", { "Martini-Henry Incendiary", AmmoType::Type::Long, 400.0f, 125, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Mosin Obrez Base", { "Mosin Obrez Base", AmmoType::Type::Long, 520.0f, 100, ActionType::BoltAction, SlotSize::Medium } },
{ "Mosin Obrez Incendiary", { "Mosin Obrez Incendiary", AmmoType::Type::Long, 520.0f, 100, ActionType::BoltAction, SlotSize::Medium } },
{ "Mosin Obrez Match Base", { "Mosin Obrez Match Base", AmmoType::Type::Long, 540.0f, 105, ActionType::BoltAction, SlotSize::Large } },
{ "Mosin Obrez Match Incendiary", { "Mosin Obrez Match Incendiary", AmmoType::Type::Long, 540.0f, 105, ActionType::BoltAction, SlotSize::Large } },
{ "Mosin-Nagant Avtomat Base", { "Mosin-Nagant Avtomat Base", AmmoType::Type::Long, 615.0f, 135, ActionType::BoltAction, SlotSize::Large } },
{ "Mosin-Nagant Avtomat Spitzer", { "Mosin-Nagant Avtomat Spitzer", AmmoType::Type::Long, 820.0f, 165, ActionType::BoltAction, SlotSize::Large } },
{ "Mosin-Nagant Avtomat Incendiary", { "Mosin-Nagant Avtomat Incendiary", AmmoType::Type::Long, 615.0f, 135, ActionType::BoltAction, SlotSize::Large } },
{ "Mosin-Nagant Base", { "Mosin-Nagant Base", AmmoType::Type::Long, 615.0f, 135, ActionType::BoltAction, SlotSize::Large } },
{ "Mosin-Nagant Spitzer", {"Mosin-Nagant Spitzer", AmmoType::Type::Spitzer, 820.0f, 165, ActionType::BoltAction, SlotSize::Large } },
{ "Mosin-Nagant Incendiary", { "Mosin-Nagant Incendiary", AmmoType::Type::Long, 615.0f, 135, ActionType::BoltAction, SlotSize::Large } },
{ "Nagant M1895 Base", { "Nagant M1895 Base", AmmoType::Type::Compact, 330.0f, 70, ActionType::SingleAction, SlotSize::Small } },
{ "Nagant M1895 Dumdum", { "Nagant M1895 Dumdum", AmmoType::Type::Compact, 300.0f, 65, ActionType::SingleAction, SlotSize::Small } },
{ "Nagant M1895 High Velocity", { "Nagant M1895 High Velocity", AmmoType::Type::Compact, 405.0f, 80, ActionType::SingleAction, SlotSize::Small } },
{ "Nagant M1895 Poison", { "Nagant M1895 Poison", AmmoType::Type::Compact, 330.0f, 70, ActionType::SingleAction, SlotSize::Small } },
{ "Nagant M1895 Silencer Base", { "Nagant M1895 Silencer Base", AmmoType::Type::Compact, 280.0f, 60, ActionType::SingleAction, SlotSize::Small } },
{ "Nagant M1895 Silencer Dumdum", { "Nagant M1895 Silencer Dumdum", AmmoType::Type::Compact, 224.0f, 50, ActionType::SingleAction, SlotSize::Small } },
{ "Nagant M1895 Silencer High Velocity", { "Nagant M1895 Silencer High Velocity", AmmoType::Type::Compact, 355.0f, 70, ActionType::SingleAction, SlotSize::Small } },
{ "Nagant M1895 Silencer Poison", { "Nagant M1895 Silencer Poison", AmmoType::Type::Compact, 280.0f, 60, ActionType::SingleAction, SlotSize::Small } },
{ "Nagant M1895 Silencer Subsonic", { "Nagant M1895 Silencer Subsonic", AmmoType::Type::Compact, 221.0f, 50, ActionType::SingleAction, SlotSize::Small } },
{ "Nagant M1895 Subsonic", { "Nagant M1895 Subsonic", AmmoType::Type::Compact, 238.0f, 55, ActionType::SingleAction, SlotSize::Small } },
{ "New Army Base", { "New Army Base", AmmoType::Type::Compact, 230.0f, 75, ActionType::DoubleAction, SlotSize::Small } },
{ "New Army Dumdum", { "New Army Dumdum", AmmoType::Type::Compact, 200.0f, 70, ActionType::DoubleAction, SlotSize::Small } },
{ "New Army FMJ", { "New Army FMJ", AmmoType::Type::Compact, 200.0f, 70, ActionType::DoubleAction, SlotSize::Small } },
{ "Nitro Express Base", { "Nitro Express Base", AmmoType::Type::Nitro, 550.0f, 45, ActionType::BreakAction, SlotSize::Large } },
{ "Nitro Express Explosive", { "Nitro Express Explosive", AmmoType::Type::Nitro, 410.0f, 20, ActionType::BreakAction, SlotSize::Large } },
{ "Nitro Express Shredder", { "Nitro Express Shredder", AmmoType::Type::Nitro, 495.0f, 40, ActionType::BreakAction, SlotSize::Large } },
{ "Officer Base", { "Officer Base", AmmoType::Type::Compact, 330.0f, 70, ActionType::DoubleAction, SlotSize::Small } },
{ "Officer Carbine Base", { "Officer Carbine Base", AmmoType::Type::Compact, 360.0f, 90, ActionType::DoubleAction, SlotSize::Medium } },
{ "Officer Carbine Dumdum", { "Officer Carbine Dumdum", AmmoType::Type::Compact, 330.0f, 85, ActionType::DoubleAction, SlotSize::Medium } },
{ "Officer Carbine High Velocity", { "Officer Carbine High Velocity", AmmoType::Type::Compact, 460.0f, 100, ActionType::DoubleAction, SlotSize::Medium } },
{ "Officer Carbine Poison", { "Officer Carbine Poison", AmmoType::Type::Compact, 360.0f, 90, ActionType::DoubleAction, SlotSize::Medium } },
{ "Officer Carbine Subsonic", { "Officer Carbine Subsonic", AmmoType::Type::Compact, 249.0f, 70, ActionType::DoubleAction, SlotSize::Medium } },
{ "Officer Dumdum", { "Officer Dumdum", AmmoType::Type::Compact, 300.0f, 65, ActionType::DoubleAction, SlotSize::Small } },
{ "Officer High Velocity", { "Officer High Velocity", AmmoType::Type::Compact, 405.0f, 80, ActionType::DoubleAction, SlotSize::Small } },
{ "Officer Poison", { "Officer Poison", AmmoType::Type::Compact, 330.0f, 70, ActionType::DoubleAction, SlotSize::Small } },
{ "Officer Subsonic", { "Officer Subsonic", AmmoType::Type::Compact, 238.0f, 55, ActionType::DoubleAction, SlotSize::Small } },
{ "Pax Base", { "Pax Base", AmmoType::Type::Medium, 330.0f, 65, ActionType::SingleAction, SlotSize::Small } },
{ "Pax Dumdum", { "Pax Dumdum", AmmoType::Type::Medium, 300.0f, 60, ActionType::SingleAction, SlotSize::Small } },
{ "Pax FMJ", { "Pax FMJ", AmmoType::Type::Medium, 300.0f, 60, ActionType::SingleAction, SlotSize::Small } },
{ "Pax High Velocity", { "Pax High Velocity", AmmoType::Type::Medium, 405.0f, 70, ActionType::SingleAction, SlotSize::Small } },
{ "Pax Incendiary", { "Pax Incendiary", AmmoType::Type::Medium, 330.0f, 65, ActionType::SingleAction, SlotSize::Small } },
{ "Pax Poison", { "Pax Poison", AmmoType::Type::Medium, 330.0f, 65, ActionType::SingleAction, SlotSize::Small } },
{ "Pax Trueshot Base", { "Pax Trueshot Base", AmmoType::Type::Medium, 410.0f, 80, ActionType::SingleAction, SlotSize::Small } },
{ "Pax Trueshot Dumdum", { "Pax Trueshot Dumdum", AmmoType::Type::Medium, 405.0f, 75, ActionType::SingleAction, SlotSize::Small } },
{ "Pax Trueshot FMJ", { "Pax Trueshot FMJ", AmmoType::Type::Medium, 405.0f, 75, ActionType::SingleAction, SlotSize::Small } },
{ "Pax Trueshot High Velocity", { "Pax Trueshot High Velocity", AmmoType::Type::Medium, 510.0f, 90, ActionType::SingleAction, SlotSize::Small } },
{ "Pax Trueshot Incendiary", { "Pax Trueshot Incendiary", AmmoType::Type::Medium, 410.0f, 80, ActionType::SingleAction, SlotSize::Small } },
{ "Pax Trueshot Poison", { "Pax Trueshot Poison", AmmoType::Type::Medium, 410.0f, 80, ActionType::SingleAction, SlotSize::Small } },
{ "Ranger 73 Base", { "Ranger 73 Base", AmmoType::Type::Compact, 400.0f, 140, ActionType::LeverAction, SlotSize::Large } },
{ "Ranger 73 FMJ", { "Ranger 73 FMJ", AmmoType::Type::Compact, 330.0f, 125, ActionType::LeverAction, SlotSize::Large } },
{ "Ranger 73 High Velocity", { "Ranger 73 High Velocity", AmmoType::Type::Compact, 500.0f, 160, ActionType::LeverAction, SlotSize::Large } },
{ "Ranger 73 Incendiary", { "Ranger 73 Incendiary", AmmoType::Type::Compact, 400.0f, 140, ActionType::LeverAction, SlotSize::Large } },
{ "Ranger 73 Poison", { "Ranger 73 Poison", AmmoType::Type::Compact, 400.0f, 140, ActionType::LeverAction, SlotSize::Large } },
{ "Ranger 73 Subsonic", { "Ranger 73 Subsonic", AmmoType::Type::Compact, 263.0f, 110, ActionType::LeverAction, SlotSize::Large } },
{ "Rival 78 Base", { "Rival 78 Base", AmmoType::Type::Shell, 425.0f, 25, ActionType::BreakAction, SlotSize::Large } },
{ "Rival 78 Dragon Breath", { "Rival 78 Dragon Breath", AmmoType::Type::Shell, 100.0f, 25, ActionType::BreakAction, SlotSize::Large } },
{ "Rival 78 Flechette", { "Rival 78 Flechette", AmmoType::Type::Shell, 425.0f, 25, ActionType::BreakAction, SlotSize::Large } },
{ "Rival 78 Penny Shot", { "Rival 78 Penny Shot", AmmoType::Type::Shell, 425.0f, 25, ActionType::BreakAction, SlotSize::Large } },
{ "Rival 78 Shorty Base", { "Rival 78 Shorty Base", AmmoType::Type::Shell, 350.0f, 20, ActionType::BreakAction, SlotSize::Medium } },
{ "Rival 78 Shorty Dragon Breath", { "Rival 78 Shorty Dragon Breath", AmmoType::Type::Shell, 100.0f, 20, ActionType::BreakAction, SlotSize::Medium } },
{ "Rival 78 Shorty Flechette", { "Rival 78 Shorty Flechette", AmmoType::Type::Shell, 350.0f, 20, ActionType::BreakAction, SlotSize::Medium } },
{ "Rival 78 Shorty Penny Shot", { "Rival 78 Shorty Penny Shot", AmmoType::Type::Shell, 350.0f, 20, ActionType::BreakAction, SlotSize::Medium } },
{ "Rival 78 Shorty Slug", { "Rival 78 Shorty Slug", AmmoType::Type::Shell, 350.0f, 20, ActionType::BreakAction, SlotSize::Medium } },
{ "Rival 78 Slug", { "Rival 78 Slug", AmmoType::Type::Shell, 425.0f, 25, ActionType::BreakAction, SlotSize::Large } },
{ "Rival 78 Trauma Base", { "Rival 78 Trauma Base", AmmoType::Type::Shell, 425.0f, 25, ActionType::BreakAction, SlotSize::Large } },
{ "Rival 78 Trauma Dragon Breath", { "Rival 78 Trauma Dragon Breath", AmmoType::Type::Shell, 100.0f, 25, ActionType::BreakAction, SlotSize::Large } },
{ "Rival 78 Trauma Flechette", { "Rival 78 Trauma Flechette", AmmoType::Type::Shell, 425.0f, 25, ActionType::BreakAction, SlotSize::Large } },
{ "Rival 78 Trauma Penny Shot", { "Rival 78 Trauma Penny Shot", AmmoType::Type::Shell, 425.0f, 25, ActionType::BreakAction, SlotSize::Large } },
{ "Rival 78 Trauma Slug", { "Rival 78 Trauma Slug", AmmoType::Type::Shell, 425.0f, 25, ActionType::BreakAction, SlotSize::Large } },
{ "Romero 77 Base", { "Romero 77 Base", AmmoType::Type::Shell, 450.0f, 30, ActionType::BreakAction, SlotSize::Large } },
{ "Romero 77 Dragon Breath", { "Romero 77 Dragon Breath", AmmoType::Type::Shell, 100.0f, 30, ActionType::BreakAction, SlotSize::Large } },
{ "Romero 77 Penny Shot", { "Romero 77 Penny Shot", AmmoType::Type::Shell, 450.0f, 30, ActionType::BreakAction, SlotSize::Large } },
{ "Romero 77 Shorty Base", { "Romero 77 Shorty Base", AmmoType::Type::Shell, 375.0f, 20, ActionType::BreakAction, SlotSize::Medium } },
{ "Romero 77 Shorty Dragon Breath", { "Romero 77 Shorty Dragon Breath", AmmoType::Type::Shell, 100.0f, 20, ActionType::BreakAction, SlotSize::Medium } },
{ "Romero 77 Shorty Penny Shot", { "Romero 77 Shorty Penny Shot", AmmoType::Type::Shell, 375.0f, 20, ActionType::BreakAction, SlotSize::Medium } },
{ "Romero 77 Shorty Slug", { "Romero 77 Shorty Slug", AmmoType::Type::Shell, 375.0f, 20, ActionType::BreakAction, SlotSize::Medium } },
{ "Romero 77 Shorty Starshell", { "Romero 77 Shorty Starshell", AmmoType::Type::Shell, 75.0f, 20, ActionType::BreakAction, SlotSize::Medium } },
{ "Romero 77 Slug", { "Romero 77 Slug", AmmoType::Type::Shell, 450.0f, 30, ActionType::BreakAction, SlotSize::Large } },
{ "Romero 77 Starshell", { "Romero 77 Starshell", AmmoType::Type::Shell, 75.0f, 30, ActionType::BreakAction, SlotSize::Large } },
{ "Scottfield Base", { "Scottfield Base", AmmoType::Type::Medium, 280.0f, 65, ActionType::SingleAction, SlotSize::Small } },
{ "Scottfield Dumdum", { "Scottfield Dumdum", AmmoType::Type::Medium, 250.0f, 60, ActionType::SingleAction, SlotSize::Small } },
{ "Scottfield FMJ", { "Scottfield FMJ", AmmoType::Type::Medium, 250.0f, 60, ActionType::SingleAction, SlotSize::Small } },
{ "Scottfield High Velocity", { "Scottfield High Velocity", AmmoType::Type::Medium, 355.0f, 75, ActionType::SingleAction, SlotSize::Small } },
{ "Scottfield Incendiary", { "Scottfield Incendiary", AmmoType::Type::Medium, 280.0f, 65, ActionType::SingleAction, SlotSize::Small } },
{ "Slate Base", { "Slate Base", AmmoType::Type::Shell, 425.0f, 25, ActionType::PumpAction, SlotSize::Large } },
{ "Slate Penny Shot", { "Slate Penny Shot", AmmoType::Type::Shell, 425.0f, 25, ActionType::PumpAction, SlotSize::Large } },
{ "Slate Slug", { "Slate Slug", AmmoType::Type::Shell, 425.0f, 25, ActionType::PumpAction, SlotSize::Large } },
{ "Sparks Base", { "Sparks Base", AmmoType::Type::Long, 533.0f, 145, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Sparks FMJ", { "Sparks FMJ", AmmoType::Type::Long, 370.0f, 125, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Sparks Incendiary", { "Sparks Incendiary", AmmoType::Type::Long, 533.0f, 145, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Sparks Pistol Base", { "Sparks Pistol Base", AmmoType::Type::Long, 453.0f, 95, ActionType::SingleShotBreechLoading, SlotSize::Small } },
{ "Sparks Pistol FMJ", { "Sparks Pistol FMJ", AmmoType::Type::Long, 362.0f, 85, ActionType::SingleShotBreechLoading, SlotSize::Small } },
{ "Sparks Pistol Incendiary", { "Sparks Pistol Incendiary", AmmoType::Type::Long, 453.0f, 95, ActionType::SingleShotBreechLoading, SlotSize::Small } },
{ "Sparks Pistol Poison", { "Sparks Pistol Poison", AmmoType::Type::Long, 453.0f, 95, ActionType::SingleShotBreechLoading, SlotSize::Small } },
{ "Sparks Pistol Silencer Base", { "Sparks Pistol Silencer Base", AmmoType::Type::Long, 385.0f, 85, ActionType::SingleShotBreechLoading, SlotSize::Small } },
{ "Sparks Pistol Silencer FMJ", { "Sparks Pistol Silencer FMJ", AmmoType::Type::Long, 308.0f, 80, ActionType::SingleShotBreechLoading, SlotSize::Small } },
{ "Sparks Pistol Silencer Incendiary", { "Sparks Pistol Silencer Incendiary", AmmoType::Type::Long, 385.0f, 85, ActionType::SingleShotBreechLoading, SlotSize::Small } },
{ "Sparks Pistol Silencer Poison", { "Sparks Pistol Silencer Poison", AmmoType::Type::Long, 385.0f, 85, ActionType::SingleShotBreechLoading, SlotSize::Small } },
{ "Sparks Pistol Silencer Subsonic", { "Sparks Pistol Silencer Subsonic", AmmoType::Type::Long, 258.0f, 75, ActionType::SingleShotBreechLoading, SlotSize::Small } },
{ "Sparks Pistol Subsonic", { "Sparks Pistol Subsonic", AmmoType::Type::Long, 281.0f, 75, ActionType::SingleShotBreechLoading, SlotSize::Small } },
{ "Sparks Poison", { "Sparks Poison", AmmoType::Type::Long, 533.0f, 145, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Sparks Silencer Base", { "Sparks Silencer Base", AmmoType::Type::Long, 453.0f, 110, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Sparks Silencer FMJ", { "Sparks Silencer FMJ", AmmoType::Type::Long, 362.0f, 95, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Sparks Silencer Incendiary", { "Sparks Silencer Incendiary", AmmoType::Type::Long, 453.0f, 110, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Sparks Silencer Poison", { "Sparks Silencer Poison", AmmoType::Type::Long, 453.0f, 110, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Sparks Silencer Subsonic", { "Sparks Silencer Subsonic", AmmoType::Type::Long, 281.0f, 85, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Sparks Subsonic", { "Sparks Subsonic", AmmoType::Type::Long, 309.0f, 115, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Specter Base", { "Specter Base", AmmoType::Type::Shell, 425.0f, 30, ActionType::PumpAction, SlotSize::Large } },
{ "Specter Dragon Breath", { "Specter Dragon Breath", AmmoType::Type::Shell, 100.0f, 30, ActionType::PumpAction, SlotSize::Large } },
{ "Specter Flechette", { "Specter Flechette", AmmoType::Type::Shell, 425.0f, 30, ActionType::PumpAction, SlotSize::Large } },
{ "Specter Penny Shot", { "Specter Penny Shot", AmmoType::Type::Shell, 425.0f, 30, ActionType::PumpAction, SlotSize::Large } },
{ "Specter Shorty Base", { "Specter Shorty Base", AmmoType::Type::Shell, 350.0f, 20, ActionType::PumpAction, SlotSize::Medium } },
{ "Specter Shorty Dragon Breath", { "Specter Shorty Dragon Breath", AmmoType::Type::Shell, 100.0f, 20, ActionType::PumpAction, SlotSize::Medium } },
{ "Specter Shorty Flechette", { "Specter Shorty Flechette", AmmoType::Type::Shell, 350.0f, 20, ActionType::PumpAction, SlotSize::Medium } },
{ "Specter Shorty Penny Shot", { "Specter Shorty Penny Shot", AmmoType::Type::Shell, 350.0f, 20, ActionType::PumpAction, SlotSize::Medium } },
{ "Specter Shorty Slug", { "Specter Shorty Slug", AmmoType::Type::Shell, 350.0f, 20, ActionType::PumpAction, SlotSize::Medium } },
{ "Specter Slug", { "Specter Slug", AmmoType::Type::Shell, 425.0f, 30, ActionType::PumpAction, SlotSize::Large } },
{ "Springfield Base", { "Springfield Base", AmmoType::Type::Medium, 490.0f, 160, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Springfield Dumdum", { "Springfield Dumdum", AmmoType::Type::Medium, 440.0f, 155, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Springfield Explosive", { "Springfield Explosive", AmmoType::Type::Medium, 370.0f, 120, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Springfield High Velocity", { "Springfield High Velocity", AmmoType::Type::Medium, 615.0f, 160, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Springfield Poison", { "Springfield Poison", AmmoType::Type::Medium, 490.0f, 160, ActionType::SingleShotBreechLoading, SlotSize::Large } },
{ "Springfield Shorty Base", { "Springfield Shorty Base", AmmoType::Type::Medium, 440.0f, 120, ActionType::SingleShotBreechLoading, SlotSize::Medium } },
{ "Springfield Shorty Dumdum", { "Springfield Shorty Dumdum", AmmoType::Type::Medium, 390.0f, 110, ActionType::SingleShotBreechLoading, SlotSize::Medium } },
{ "Springfield Shorty Explosive", { "Springfield Shorty Explosive", AmmoType::Type::Medium, 330.0f, 80, ActionType::SingleShotBreechLoading, SlotSize::Medium } },
{ "Springfield Shorty High Velocity", { "Springfield Shorty High Velocity", AmmoType::Type::Medium, 515.0f, 130, ActionType::SingleShotBreechLoading, SlotSize::Medium } },
{ "Springfield Shorty Poison", { "Springfield Shorty Poison", AmmoType::Type::Medium, 440.0f, 120, ActionType::SingleShotBreechLoading, SlotSize::Medium } },
{ "Terminus Base", { "Terminus Base", AmmoType::Type::Shell, 425.0f, 25, ActionType::PumpAction, SlotSize::Large } },
{ "Terminus Dragon Breath", { "Terminus Dragon Breath", AmmoType::Type::Shell, 100.0f, 25, ActionType::PumpAction, SlotSize::Large } },
{ "Terminus Flechette", { "Terminus Flechette", AmmoType::Type::Shell, 425.0f, 25, ActionType::PumpAction, SlotSize::Large } },
{ "Terminus Penny Shot", { "Terminus Penny Shot", AmmoType::Type::Shell, 425.0f, 25, ActionType::PumpAction, SlotSize::Large } },
{ "Terminus Shorty Base", { "Terminus Shorty Base", AmmoType::Type::Shell, 350.0f, 20, ActionType::PumpAction, SlotSize::Medium } },
{ "Terminus Shorty Dragon Breath", { "Terminus Shorty Dragon Breath", AmmoType::Type::Shell, 100.0f, 20, ActionType::PumpAction, SlotSize::Medium } },
{ "Terminus Shorty Flechette", { "Terminus Shorty Flechette", AmmoType::Type::Shell, 350.0f, 20, ActionType::PumpAction, SlotSize::Medium } },
{ "Terminus Shorty Penny Shot", { "Terminus Shorty Penny Shot", AmmoType::Type::Shell, 350.0f, 20, ActionType::PumpAction, SlotSize::Medium } },
{ "Terminus Shorty Slug", { "Terminus Shorty Slug", AmmoType::Type::Shell, 350.0f, 20, ActionType::PumpAction, SlotSize::Medium } },
{ "Terminus Slug", { "Terminus Slug", AmmoType::Type::Shell, 425.0f, 25, ActionType::PumpAction, SlotSize::Large } },
{ "Uppercut Base", { "Uppercut Base", AmmoType::Type::Long, 410.0f, 65, ActionType::SingleAction, SlotSize::Small } },
{ "Uppercut Explosive", { "Uppercut Explosive", AmmoType::Type::Long, 330.0f, 45, ActionType::SingleAction, SlotSize::Small } },
{ "Uppercut FMJ", { "Uppercut FMJ", AmmoType::Type::Long, 360.0f, 60, ActionType::SingleAction, SlotSize::Small } },
{ "Uppercut Incendiary", { "Uppercut Incendiary", AmmoType::Type::Long, 410.0f, 65, ActionType::SingleAction, SlotSize::Small } },
{ "Vandal 73C Base", { "Vandal 73C Base", AmmoType::Type::Compact, 370.0f, 120, ActionType::LeverAction, SlotSize::Medium } },
{ "Vandal 73C FMJ", { "Vandal 73C FMJ", AmmoType::Type::Compact, 310.0f, 110, ActionType::LeverAction, SlotSize::Medium } },
{ "Vandal 73C High Velocity", { "Vandal 73C High Velocity", AmmoType::Type::Compact, 470.0f, 145, ActionType::LeverAction, SlotSize::Medium } },
{ "Vandal 73C Incendiary", { "Vandal 73C Incendiary", AmmoType::Type::Compact, 370.0f, 120, ActionType::LeverAction, SlotSize::Medium } },
{ "Vandal 73C Poison", { "Vandal 73C Poison", AmmoType::Type::Compact, 370.0f, 120, ActionType::LeverAction, SlotSize::Medium } },
{ "Vandal 73C Subsonic", { "Vandal 73C Subsonic", AmmoType::Type::Compact, 252.0f, 95, ActionType::LeverAction, SlotSize::Medium } },
{ "Vetterli 71 Base", { "Vetterli 71 Base", AmmoType::Type::Medium, 410.0f, 125, ActionType::BoltAction, SlotSize::Large } },
{ "Vetterli 71 Cyclone Base", { "Vetterli 71 Cyclone Base", AmmoType::Type::Medium, 410.0f, 105, ActionType::SemiAuto, SlotSize::Large } },
{ "Vetterli 71 Cyclone FMJ", { "Vetterli 71 Cyclone FMJ", AmmoType::Type::Medium, 350.0f, 95, ActionType::SemiAuto, SlotSize::Large } },
{ "Vetterli 71 Cyclone High Velocity", { "Vetterli 71 Cyclone High Velocity", AmmoType::Type::Medium, 510.0f, 120, ActionType::SemiAuto, SlotSize::Large } },
{ "Vetterli 71 Cyclone Incendiary", { "Vetterli 71 Cyclone Incendiary", AmmoType::Type::Medium, 410.0f, 105, ActionType::SemiAuto, SlotSize::Large } },
{ "Vetterli 71 Cyclone Subsonic", { "Vetterli 71 Cyclone Subsonic", AmmoType::Type::Medium, 266.0f, 80, ActionType::SemiAuto, SlotSize::Large } },
{ "Vetterli 71 FMJ", { "Vetterli 71 FMJ", AmmoType::Type::Medium, 350.0f, 115, ActionType::BoltAction, SlotSize::Large } },
{ "Vetterli 71 High Velocity", { "Vetterli 71 High Velocity", AmmoType::Type::Medium, 510.0f, 140, ActionType::BoltAction, SlotSize::Large } },
{ "Vetterli 71 Incendiary", { "Vetterli 71 Incendiary", AmmoType::Type::Medium, 410.0f, 125, ActionType::BoltAction, SlotSize::Large } },
{ "Vetterli 71 Silencer Base", { "Vetterli 71 Silencer Base", AmmoType::Type::Medium, 348.0f, 115, ActionType::BoltAction, SlotSize::Large } },
{ "Vetterli 71 Silencer FMJ", { "Vetterli 71 Silencer FMJ", AmmoType::Type::Medium, 278.0f, 105, ActionType::BoltAction, SlotSize::Large } },
{ "Vetterli 71 Silencer High Velocity", { "Vetterli 71 Silencer High Velocity", AmmoType::Type::Medium, 448.0f, 130, ActionType::BoltAction, SlotSize::Large } },
{ "Vetterli 71 Silencer Incendiary", { "Vetterli 71 Silencer Incendiary", AmmoType::Type::Medium, 348.0f, 115, ActionType::BoltAction, SlotSize::Large } },
{ "Vetterli 71 Silencer Subsonic", { "Vetterli 71 Silencer Subsonic", AmmoType::Type::Medium, 245.0f, 100, ActionType::BoltAction, SlotSize::Large } },
    { "Vetterli 71 Subsonic", { "Vetterli 71 Subsonic", AmmoType::Type::Medium, 266.0f, 100, ActionType::BoltAction, SlotSize::Large } }

};

// --- Weapon preset entry for the ImGui menu dropdown ---
struct WeaponPresetEntry {
    const char* name;
    float bulletSpeed;
    float dropRange;
    int ammoType; // Simplified: 0=Compact/Other, 1=Medium, 2=Long
};

inline int GetSimplifiedAmmoType(AmmoType::Type type) {
    switch (type) {
        case AmmoType::Medium: return 1;
        case AmmoType::Long:
        case AmmoType::Spitzer:
        case AmmoType::Nitro:
            return 2;
        default: return 0;
    }
}

inline const int WeaponNameCount = sizeof(weaponNames) / sizeof(weaponNames[0]);
inline const int WeaponPresetCount = WeaponNameCount + 1; // +1 for "Custom" at index 0

inline WeaponPresetEntry GetWeaponPresetEntry(int index) {
    if (index <= 0) return { "Custom", 500.0f, 200.0f, 0 };
    if (index > WeaponNameCount) return { "Custom", 500.0f, 200.0f, 0 };
    const char* wName = weaponNames[index - 1];
    auto it = weapons.find(wName);
    if (it != weapons.end()) {
        const Weapon& w = it->second;
        return { wName, w.muzzleVelocity, (float)w.dropRange, GetSimplifiedAmmoType(w.ammoType) };
    }
    return { wName, 500.0f, 200.0f, 0 };
}

// Static array built at startup for fast indexed access
struct WeaponPresetsArray {
    WeaponPresetEntry entries[sizeof(weaponNames) / sizeof(weaponNames[0]) + 1];
    WeaponPresetsArray() {
        entries[0] = { "Custom", 500.0f, 200.0f, 0 };
        for (int i = 0; i < WeaponNameCount; i++) {
            entries[i + 1] = GetWeaponPresetEntry(i + 1);
        }
    }
};

inline WeaponPresetsArray _weaponPresetsArray;
inline WeaponPresetEntry* WeaponPresets = _weaponPresetsArray.entries;

